//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.Keyboard.Illuminator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSI.Keyboard.Illuminator.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of an application settings has failed!
        ///Make sure a file is not corrupted..
        /// </summary>
        public static string AppSettingsLoadingErrorMessage {
            get {
                return ResourceManager.GetString("AppSettingsLoadingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application settings failed!.
        /// </summary>
        public static string AppSettingsLoadingErrorTitle {
            get {
                return ResourceManager.GetString("AppSettingsLoadingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving of an application settings has failed!
        ///Make sure a target directory exists and You have an access to it..
        /// </summary>
        public static string AppSettingsSavingErrorMessage {
            get {
                return ResourceManager.GetString("AppSettingsSavingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving application settings failed!.
        /// </summary>
        public static string AppSettingsSavingErrorTitle {
            get {
                return ResourceManager.GetString("AppSettingsSavingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change MSI keyboard colors!.
        /// </summary>
        public static string AppTrayIconTooltipText {
            get {
                return ResourceManager.GetString("AppTrayIconTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the command line arguments has failed!
        ///The default values will be used..
        /// </summary>
        public static string CmdLineArgsParsingErrorMessage {
            get {
                return ResourceManager.GetString("CmdLineArgsParsingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments parsing failed!.
        /// </summary>
        public static string CmdLineArgsParsingErrorTitle {
            get {
                return ResourceManager.GetString("CmdLineArgsParsingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing keyboard colors has failed!
        ///Make sure the supported &quot;MSI EPF USB&quot; SteelSeries keyboard is connected!.
        /// </summary>
        public static string ColorChangeErrorMessage {
            get {
                return ResourceManager.GetString("ColorChangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing keyboard colors failed!.
        /// </summary>
        public static string ColorChangeErrorTitle {
            get {
                return ResourceManager.GetString("ColorChangeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new color profile.
        /// </summary>
        public static string ColorProfileAddTooltipText {
            get {
                return ResourceManager.GetString("ColorProfileAddTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinking.
        /// </summary>
        public static string ColorProfileBlinkingModeLabelText {
            get {
                return ResourceManager.GetString("ColorProfileBlinkingModeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string ColorProfileCenterLabelText {
            get {
                return ResourceManager.GetString("ColorProfileCenterLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string ColorProfileLeftLabelText {
            get {
                return ResourceManager.GetString("ColorProfileLeftLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected color profile down.
        /// </summary>
        public static string ColorProfileMoveDownTooltipText {
            get {
                return ResourceManager.GetString("ColorProfileMoveDownTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected color profile up.
        /// </summary>
        public static string ColorProfileMoveUpTooltipText {
            get {
                return ResourceManager.GetString("ColorProfileMoveUpTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColorProfileNameLabelText {
            get {
                return ResourceManager.GetString("ColorProfileNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected color profile.
        /// </summary>
        public static string ColorProfileRemoveTooltipText {
            get {
                return ResourceManager.GetString("ColorProfileRemoveTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string ColorProfileRightLabelText {
            get {
                return ResourceManager.GetString("ColorProfileRightLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string ColorProfilesButtonText {
            get {
                return ResourceManager.GetString("ColorProfilesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ColorProfilesCancelButtonText {
            get {
                return ResourceManager.GetString("ColorProfilesCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all color profile changes.
        /// </summary>
        public static string ColorProfilesCancelButtonTooltipText {
            get {
                return ResourceManager.GetString("ColorProfilesCancelButtonTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ColorProfilesSaveButtonText {
            get {
                return ResourceManager.GetString("ColorProfilesSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all color profile changes.
        /// </summary>
        public static string ColorProfilesSaveButtonTooltipText {
            get {
                return ResourceManager.GetString("ColorProfilesSaveButtonTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit color profiles.
        /// </summary>
        public static string ColorProfilesWindowTitle {
            get {
                return ResourceManager.GetString("ColorProfilesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string DefaultProfileName {
            get {
                return ResourceManager.GetString("DefaultProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supported &quot;MSI EPF USB&quot; SteelSeries keyboard has not been found!
        ///Exit an application as it is is not going to work properly anyway..
        /// </summary>
        public static string DeviceNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("DeviceNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSI keyboard not found!.
        /// </summary>
        public static string DeviceNotFoundErrorTitle {
            get {
                return ResourceManager.GetString("DeviceNotFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButtonText {
            get {
                return ResourceManager.GetString("ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MessageCloseButtonText {
            get {
                return ResourceManager.GetString("MessageCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close a window.
        /// </summary>
        public static string MessageCloseButtonTooltipText {
            get {
                return ResourceManager.GetString("MessageCloseButtonTooltipText", resourceCulture);
            }
        }
    }
}
