name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    env:
      version: 1.0.0.0
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        runtime: [win-x64, linux-x64]
        exclude:
          - os: windows-latest
            runtime: linux-x64
          - os: ubuntu-latest
            runtime: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'

      - name: Publish 'MSI Keyboard Illuminator'
        run: dotnet publish 'MSI.Keyboard.Illuminator/MSI.Keyboard.Illuminator.csproj' -o 'binaries' -c 'Release' -r '${{ matrix.runtime }}' -v 'normal' -p:Version=${{ env.version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: MSI.Keyboard.Illuminator_${{ matrix.runtime }}_${{ env.version }}
          path: binaries/
